// Review choices stay in this browser. No chat excerpts or profile data are stored here.
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const basisLabels={mentioned:'You mentioned it',related:'Related to your interests',intuition:'Intuition-led idea'};
let reviews={};try{reviews=JSON.parse(localStorage.getItem('monterey-activity-review-v1')||'{}')}catch{}
const style=document.createElement('style');style.textContent=`
.activity-icon{position:relative;width:37px;height:37px;display:inline-flex;align-items:center;justify-content:center;background:white;border:2px solid #267969;border-radius:11px;box-shadow:0 2px 6px #1234;flex:none;font-size:25px;vertical-align:middle}
.activity-icon img{width:25px;height:25px;object-fit:contain}.activity-icon sub{position:absolute;right:-7px;bottom:-7px;font:700 10px system-ui;border:1px solid white;border-radius:6px;background:#164b45;color:white;padding:1px 4px;line-height:14px}.card-head{display:flex;gap:13px;align-items:center;margin-bottom:10px}.card-head h3{margin:0}.basis{display:inline-block;font-size:10px;border-radius:4px;padding:3px 5px;background:#e6f3ea;margin:4px 0}.basis.intuition{background:#fff0d3}.basis.related{background:#e7eef9}.review-choice{width:100%;font-size:12px;margin-top:9px}.unlocated{border-style:dashed}.cluster-icon{background:#164b45;border:2px solid white;border-radius:12px;color:white;display:flex;align-items:center;justify-content:center;width:42px;height:38px;font-size:13px;box-shadow:0 2px 6px #0004}
#reviewDialog{border:0;border-radius:15px;width:min(1250px,96vw);max-height:90dvh;padding:22px;background:#f5f7f5;color:#143438}#reviewDialog::backdrop{background:#092629aa}.review-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:12px}.review-grid .card{margin:0;cursor:default}.review-top{position:sticky;top:-22px;z-index:3;background:#f5f7f5;padding:12px 0;border-bottom:1px solid #c4d2ca;margin-bottom:15px}.review-note{font-size:11px;color:#5d716b}.pick-actions{display:flex;gap:8px;flex-wrap:wrap}.candidate-intro{border-left:3px solid #408b7e;padding-left:9px}.overlap{font-size:11px;color:#75590e}.review-grid h3{font-size:14px}.review-summary{font-size:12px;color:#547065}.leaflet-marker-icon:focus{outline:3px solid #ebae39}
`;document.head.appendChild(style);
function emojiURL(s){return 'https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/'+[...s].filter(c=>c.codePointAt(0)!==0xfe0f).map(c=>c.codePointAt(0).toString(16)).join('-')+'.svg'}
function iconHTML(a){return `<span class="activity-icon" title="${safe(a.kind)}"><img src="${emojiURL(a.icon)}" alt="${safe(a.kind)}" loading="lazy" onerror="this.replaceWith(document.createTextNode(this.dataset.emoji))" data-emoji="${safe(a.icon)}"><sub>${a.id}</sub></span>`}
function activityIcon(a){return L.divIcon({className:'activity-pin',html:iconHTML(a),iconSize:[37,37],iconAnchor:[18,18]})}
function reviewSelect(a){return `<select class="review-choice" data-review="${a.id}" aria-label="Review ${safe(a.name)}">${[['unreviewed','Not reviewed'],['keep','Keep — I like this'],['maybe','Maybe / needs research'],['duplicate','Possible duplicate'],['skip','Skip — not for me']].map(([v,t])=>`<option value="${v}" ${(reviews[a.id]||'unreviewed')===v?'selected':''}>${t}</option>`).join('')}</select>`}
function bindReviews(container){container.querySelectorAll('[data-review]').forEach(el=>{el.onclick=e=>e.stopPropagation();el.onchange=e=>{e.stopPropagation();reviews[el.dataset.review]=el.value;try{localStorage.setItem('monterey-activity-review-v1',JSON.stringify(reviews))}catch{}updateReviewSummary()}})}
function updateReviewSummary(){const tally={keep:0,maybe:0,duplicate:0,skip:0};Object.values(reviews).forEach(v=>{if(v in tally)tally[v]++});document.querySelectorAll('.review-summary').forEach(e=>e.textContent=`${tally.keep} keep · ${tally.maybe} maybe · ${tally.duplicate} possible duplicates · ${tally.skip} skip. Saved only in this browser.`)}
reachMenu.querySelector('option[value="all"]').textContent='All 100 candidates';
intro.className='subtle candidate-intro';intro.textContent='100 ideas to review—not 100 proven favorites. Icons identify the activity; the small badge is its ID. Mentioned, related and intuition-led ideas are labeled separately. Some specialist ideas remain unmapped until a real venue is verified.';
const reviewTools=document.createElement('div');reviewTools.innerHTML=`<div class="pick-actions"><button id="reviewAll">Review all 100 icons</button><button id="exportReview">Export my review</button></div><p class="review-summary"></p><div class="toolbar"><select id="basis"><option value="all">All evidence levels</option><option value="mentioned">You mentioned it</option><option value="related">Related ideas</option><option value="intuition">Intuition-led ideas</option></select><select id="reviewFilter"><option value="all">All review states</option><option value="keep">Keep</option><option value="maybe">Maybe</option><option value="duplicate">Possible duplicates</option><option value="skip">Skip</option><option value="unreviewed">Not reviewed</option><option value="unlocated">Needs a verified venue</option></select></div>`;intro.after(reviewTools);
$('category').querySelector('[value="harvest"]').textContent='Food, growing & harvesting';
$('category').querySelector('[value="creative"]').textContent='Arts, making & photography';
function matches(a){const reach=$('reach').value,mode=reach==='flex'?'drive':reach,r=a.travel?.[mode],rf=$('reviewFilter').value;return ($('category').value==='all'||a.category===$('category').value)&&($('basis').value==='all'||a.interestBasis===$('basis').value)&&(rf==='all'||(rf==='unlocated'?a.unlocated:(reviews[a.id]||'unreviewed')===rf))&&(reach==='all'||(r&&!r.error&&r.minutes<=({walk:15,bike:30,drive:120,flex:150}[reach])))&&`${a.name} ${a.place} ${a.kind} ${a.id}`.toLowerCase().includes($('search').value.toLowerCase())}
filtered=()=>D.activities.filter(matches);
function cardContent(a,review=false){return `<div class="card-head">${iconHTML(a)}<div><h3>${safe(a.name)}</h3><span class="basis ${a.interestBasis}">${basisLabels[a.interestBasis]}</span></div></div><div>${safe(a.place)}</div>${a.unlocated?'<p class="warning">No verified local venue yet. No invented pin, route or travel time.</p>':travelHTML(a)}<p class="subtle">${safe(a.why)}</p>${a.note&&/overlap|related to|shares/i.test(a.note)?'<p class="overlap">Possible overlap — review the access notes.</p>':''}${review?`<p class="review-note">${safe(a.note||a.accessStatus)}</p>`:''}${reviewSelect(a)}${review?`<button data-open="${a.id}" style="margin-top:8px">${a.unlocated?'View research gap':'Show location & route'}</button>`:`<p class="subtle">${a.unlocated?'Select for research notes':`Suggested mode: ${choose(a)} · select for route & details`}</p>`}`}
localRender=function(){pins.clearLayers();paths.clearLayers();const items=filtered(),mapped=items.filter(a=>!a.unlocated);$('count').textContent=`${items.length} candidates · ${mapped.length} mapped · ${items.length-mapped.length} venue gaps · travel one way`;$('list').innerHTML='';const group=L.markerClusterGroup?L.markerClusterGroup({maxClusterRadius:43,spiderfyOnMaxZoom:true,showCoverageOnHover:false,zoomToBoundsOnClick:true,iconCreateFunction:c=>L.divIcon({className:'',html:`<div class="cluster-icon" title="Zoom to reveal ${c.getChildCount()} activity icons">🗺️ +${c.getChildCount()}</div>`,iconSize:[42,38]})}):L.layerGroup();group.addTo(pins);items.forEach(a=>{if(!a.unlocated)L.marker(ll(a),{icon:activityIcon(a),title:`${a.id}. ${a.name}`,keyboard:true}).bindTooltip(`${a.icon} ${a.id}. ${safe(a.name)} — ${safe(a.place)}`).on('click',()=>select(a.id)).addTo(group);const c=document.createElement('article');c.className='card'+(selected===a.id?' selected':'')+(a.unlocated?' unlocated':'');c.dataset.activity=a.id;c.innerHTML=cardContent(a);c.onclick=()=>select(a.id);$('list').appendChild(c);if($('allRoutes').checked&&!a.unlocated){const mode=$('mode').value==='auto'?choose(a):$('mode').value;line(a.travel[mode],colors[mode],`${a.name} · ${mode}`,2)}});bindReviews($('list'));if(selected&&!$('allRoutes').checked){const a=D.activities.find(x=>x.id===selected);if(!a.unlocated){const m=$('mode').value==='auto'?choose(a):$('mode').value;line(a.travel[m],colors[m],`${a.name} · ${m}`)}}updateReviewSummary()};
const priorSelect=select;select=async function(id){const a=D.activities.find(x=>x.id===id);if(a.unlocated){selected=id;localRender();$('detail').innerHTML=`<h2>${iconHTML(a)} ${safe(a.name)}</h2><p class="warning">Research gap—not a mapped destination.</p><p>${safe(a.why)}</p><p>${safe(a.note)}</p><p class="subtle">A wish-list item is not proof that the Monterey area offers this activity. This gap should count against the home base if the activity is essential.</p>`;return}await priorSelect(id);if(selected!==id)return;const h=$('detail').querySelector('h2');h.insertAdjacentHTML('afterbegin',iconHTML(a)+' ');h.insertAdjacentHTML('afterend',`<p><span class="basis ${a.interestBasis}">${basisLabels[a.interestBasis]}</span></p><p class="subtle">${safe(a.pinAccuracy)}. Routes follow mapped roads/paths to the reference pin, not a verified final entrance. Check the venue before travel.</p>`)};
['basis','reviewFilter'].forEach(id=>$(id).onchange=()=>{selected=null;$('detail').innerHTML='';localRender()});
$('allPicks').onclick=()=>map.fitBounds([origin,...filtered().filter(a=>!a.unlocated).map(ll)],{padding:[30,30],maxZoom:15});
const dialog=document.createElement('dialog');dialog.id='reviewDialog';document.body.appendChild(dialog);
$('reviewAll').onclick=()=>{dialog.innerHTML=`<div class="review-top"><div class="pick-actions"><h2 style="margin-right:auto">All 100 — your manual review</h2><button id="closeReview">Back to map</button></div><p class="subtle">One icon per idea, ID beneath it. Shared venues do not mean identical activities; mark overlaps yourself. Unmapped ideas have no verified destination. Times are one-way travel, not activity duration.</p><p class="review-summary"></p></div><div class="review-grid">${D.activities.map(a=>`<article class="card ${a.unlocated?'unlocated':''}">${cardContent(a,true)}</article>`).join('')}</div>`;bindReviews(dialog);$('closeReview').onclick=()=>{dialog.close();localRender()};dialog.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{dialog.close();if(view!=='local')setView('local');select(Number(b.dataset.open))});updateReviewSummary();dialog.showModal()};
$('exportReview').onclick=()=>{const result={created:new Date().toISOString(),origin:'Illustrative Pacific Grove / New Monterey reference—not an actual home',method:D.candidateMethod,activities:D.activities.map(a=>({id:a.id,icon:a.icon,activity:a.name,place:a.place,interestBasis:a.interestBasis,review:reviews[a.id]||'unreviewed',unlocated:!!a.unlocated,note:a.note,source:a.source}))};const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='monterey-100-activity-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
updateReviewSummary();if(D&&view==='local')localRender();
const credits=document.createElement('p');credits.className='subtle';credits.innerHTML='<a href="ACTIVITY_REVIEW.md" target="_blank">Review methodology & gaps</a> · Pictorial icons: <a href="https://github.com/jdecked/twemoji" target="_blank">Twemoji</a>, CC-BY 4.0, with emoji fallback.';document.querySelector('aside > details').appendChild(credits);
