// Public activity ideas only. No private chat text, profile details or home address.
import fs from 'node:fs';
const root=new URL('./',import.meta.url),read=n=>JSON.parse(fs.readFileSync(new URL(n,root)));
const data=read('map-data.json');
const venue={
 mpc:['Monterey Peninsula College · campus reference',36.5901,-121.8845,'https://www.mpc.edu/academics/find-a-class.html'],
 sports:['Monterey Sports Center',36.5974,-121.8907,'https://monterey.gov/sportscenter'],
 cabrillo:['Cabrillo College · Aptos campus reference',36.9892,-121.9252,'https://extension.cabrillo.edu/classes/cabrilloarts/'],
 happy:['Happy Girl Kitchen · Pacific Grove',36.6151,-121.9013,'https://happygirlkitchen.com/pages/workshops'],
 courts:['Morris Dill courts · 515 Junipero Avenue',36.6166,-121.9205,'https://files.cityofpacificgrove.org/Document_Center/Form/Recreation/ballfield-courts-application%20FY%2025-26.pdf'],
 lovers:['Lovers Point · shore access reference',36.6266,-121.9163,'https://www.pacificgrove.org/things-to-do/'],
 circus:['Radical Movement Factory · 2801 Mission Street Extension',36.959,-122.0571,'https://www.radicalmovementfactory.com/'],
 hakone:['Hakone Estate & Gardens · Saratoga',37.2544,-122.0328,'https://www.hakone.com/classes'],
 pg:['Pacific Grove Public Library',36.6201,-121.9192,'https://ffpgpl.org/book-club/'],
 museum:['Pacific Grove Museum of Natural History',36.6219,-121.9177,'https://www.pgmuseum.org/'],
 pending:['Venue / access not yet verified',null,null,''],
};
// name | venue key | category | interest basis | rationale | access/overlap note
const rows=[
 ['Spearfishing finfish','pending','harvest','mentioned','Combines underwater skill with your interest in harvesting food.','Exact legal water, season, species and safe entry still need verification; not a reserve pin.'],
 ['Surfcasting from the beach','pending','harvest','related','A shore-based alternative to charter fishing.','Need a vetted legal beach and current regulations; overlaps with fishing #15 and #31.'],
 ['Crabbing with traps or snares','pending','harvest','related','Adds a different harvesting technique.','Closures, gear rules, health advisories and legal location must be checked before mapping.'],
 ['Seaweed identification & legal harvesting','pending','harvest','mentioned','Connects marine plants, food and biodiversity.','No harvesting site asserted; protected areas, species rules and water quality require checking.'],
 ['Guided mushroom identification','pending','nature','related','An edible-ecology learning experience beyond the coast.','Fungus Federation forays have changing meeting sites: https://www.ffsc.us/info/about-forays . Not an independent edible-species identification guide.'],
 ['Pick seasonal fruit','gizdich','harvest','intuition','Hands-on food sourcing with a changing seasonal reward.','Seasonal U-pick; confirm crop, opening and exact field before driving.'],
 ['Grow food in a community garden','garden','harvest','related','A more dependable complement to ocean food than relying entirely on wild harvest.','Plot availability and ongoing responsibilities must be arranged; not drop-in harvesting.'],
 ['Take a hands-on cooking workshop','happy','learning','mentioned','Turns your cooking interest and local ingredients into a practical skill.','Book a scheduled class; not a daily drop-in activity.'],
 ['Learn preserving & fermentation','happy','learning','related','Makes seasonal ingredients useful beyond the day you collect them.','Confirm workshop topic; related to cooking #38, but a different food skill.'],
 ['Shop a growers market for a seasonal meal','market','harvest','intuition','Food variety and conversations with producers without assuming every meal is wild-caught.','Market is date/time dependent; this is ingredient sourcing, not foraging.'],
 ['Learn rowing on a reservoir','rowing','ocean','related','Full-body water movement with a different rhythm from kayaking.','Adult learn-to-row sessions; register and confirm boathouse entry.'],
 ['Learn windsurfing','shoreline','ocean','intuition','A wind-powered balance skill on protected water.','Lesson and rental availability are weather dependent.'],
 ['Open-water swimming','lovers','ocean','mentioned','A simpler daily water session than carrying scuba gear.','Use supervised instruction or a suitable buddy; currents, surf and cold matter. Shares entry with snorkeling #1.'],
 ['Lap swimming & stroke practice','sports','fitness','related','A predictable pool option when the ocean is unsuitable.','Check lap-lane schedule and admission.'],
 ['Learn capoeira','capoeira','fitness','related','Movement, rhythm and coordination fit your interest in mobility-oriented sports.','Provider reference; confirm adult class location and timetable, not a claim that every session meets here.'],
 ['Learn parkour','parkour','fitness','intuition','A coached, playful way to learn movement skills.','Confirm teen/adult session and registration; do not substitute unsupervised risky jumps.'],
 ['Try aerial arts','circus','fitness','intuition','A strong candidate for your climbing, skill-learning and visual interests.','Coached class; choose appropriate beginner level.'],
 ['Learn floor acrobatics','circus','fitness','related','Another movement discipline to test against your interest in flexibility and coordination.','Confirm current adult floor-acrobatics offering; overlaps with aerial arts #47.'],
 ['Strength training','sports','fitness','mentioned','Supports a consistent indoor training option.','Check membership and equipment; no special medical benefits claimed.'],
 ['Yoga & mobility practice','sports','fitness','mentioned','A structured movement practice you have discussed.','Select an appropriate class with the instructor; no promise of injury prevention.'],
 ['Try Pilates','sports','fitness','intuition','A controlled-movement alternative worth comparing with yoga.','Confirm current class schedule; possible overlap with #50.'],
 ['Play tennis','courts','fitness','intuition','A fast, skill-based outdoor game.','Check court allocation and booking rules.'],
 ['Play pickleball','courts','fitness','intuition','An accessible social racquet-sport experiment.','Tennis and pickleball share courts; possible overlap with #52.'],
 ['Play beach volleyball','lovers','fitness','related','Sand, coordination and a game rather than only an endurance workout.','Bring partners/equipment and check court availability. Not a sepak takraw class.'],
 ['Play table tennis','sports','fitness','intuition','Quick reactions and skill practice for gray-weather days.','Check current drop-in session and equipment availability.'],
 ['Try badminton','pending','fitness','intuition','Fast footwork and a distinctive racquet-sport option.','Public adult access at a suitable local venue remains unverified.'],
 ['Learn sepak takraw','pending','fitness','mentioned','A specific sport you asked to learn—not a generic guess.','No specialist beginner provider verified in the day-trip radius. Kept visible instead of inventing a court or class.'],
 ['Try deep-water soloing','pending','fitness','intuition','A speculative intersection of climbing and water interests.','No vetted local site/provider. Do not treat a coastal cliff as a safe substitute.'],
 ['Outdoor bouldering on sandstone','castle','fitness','mentioned','Adds real outdoor bouldering to the indoor gym option.','Do not climb wet sandstone; check closures and bring appropriate partners/pads. Related to climbing #19/#25.'],
 ['Ice skating','ice','fitness','related','A small winter-style outing without waiting for Tahoe.','Public session times and admission vary.'],
 ['Inline or roller skating','trail','fitness','intuition','A different wheeled skill along the coast.','Check posted trail rules and busy sections; shares scenery with cycling #9.'],
 ['Bodyweight strength / calisthenics','sports','fitness','related','A skill-based training alternative to weight lifting.','Facility exercise candidate, not a verified dedicated calisthenics class. Overlap with strength #49.'],
 ['Play chess with others','chess','learning','related','A strategy-game option to balance the physical activities.','Adult/family event dates must be checked; the regular after-school program is for children.'],
 ['Play strategy board games','pending','learning','related','Fits the interest in games and learning found in your discussions.','Local public game-night venue and current adult schedule still need verification.'],
 ['Join a book discussion','pg','learning','mentioned','An explicitly mentioned interest with a local community option.','Check the next meeting, title and actual meeting location.'],
 ['Study a language','mpc','learning','related','Fits your interest in words, culture and learning.','Campus reference only; check term, delivery mode and course eligibility.'],
 ['Learn coding / creative computing','mpc','learning','mentioned','A local learning avenue related to your coding/book interests.','Confirm an appropriate in-person course; not a verified drop-in coding club.'],
 ['Hands-on science & design exhibits','tech','learning','intuition','Interactive exploration rather than a purely passive museum visit.','Check exhibits, tickets and hours; workshops are not guaranteed with admission.'],
 ['Make ceramics','mpc','creative','intuition','Tactile making and a new visual medium.','Enrollment and studio access required; verify current course.'],
 ['Learn painting','mpc','creative','related','A way to interpret the scenery you want to photograph.','Current class required; distinct medium but overlaps with drawing #71.'],
 ['Learn observational drawing','mpc','creative','intuition','Slow visual attention and a portable creative skill.','Check current class and materials.'],
 ['Try glass art','cabrillo','creative','intuition','A material-and-light craft that could suit your visual interests.','Specific workshop and location must be confirmed before travel.'],
 ['Make jewelry / small metal art','cabrillo','creative','intuition','Fine hands-on work with a tangible finished object.','Check current offering, tools and prerequisites.'],
 ['Learn printmaking','mpc','creative','intuition','A different image-making process from photography.','Check term availability and studio rules.'],
 ['Learn sewing & repair','pending','creative','intuition','Useful making skills for clothing and gear, not just decoration.','A suitable local adult class has not yet been verified.'],
 ['Learn woodworking / cabinetry','cabrillo','creative','intuition','Build useful objects and understand materials.','Program reference: check a suitable introductory course and campus; not a confirmed one-day workshop.'],
 ['Practice creative writing','mpc','creative','related','A possible extension of books, observation and storytelling.','Check current writing course and delivery mode.'],
 ['Learn an instrument','mpc','creative','intuition','A different long-term mastery project.','Instrument, instruction level and enrollment need choosing; no specific lesson vacancy asserted.'],
 ['Try acting / theatre practice','mpc','creative','intuition','A new creative mode rather than another sightseeing destination.','Check auditions, class access and schedule.'],
 ['Take a dance class','mpc','fitness','related','Rhythm and movement as a skill rather than a workout only.','Choose one beginner style after checking the current schedule; not five duplicate dance pins.'],
 ['See a film on a cinema screen','cinema','creative','related','An outing connected to your saved film interests.','Check current screenings and operating hours.'],
 ['See live theatre','theatre','creative','intuition','A quiet-town cultural option with a different experience from cinema.','Ticketed, scheduled productions.'],
 ['Hear live music at Sunset Center','sunset','creative','intuition','A varied cultural option without making nightlife/drinking the focus.','Check the actual artist/program; not all events are classical.'],
 ['Explore local history & architecture','mission','learning','intuition','Built history adds a different kind of place-learning to nature outings.','Respect religious services and visitor access rules.'],
 ['See a planetarium program','planet','learning','related','A weather-independent counterpart to stargazing.','Check public-show dates; a college planetarium is not open continuously.'],
 ['Explore marine research exhibits','seymour','learning','related','Connects the animals you film with marine science.','Museum visit, not permission to enter research labs; overlaps with aquarium #11.'],
 ['Learn local natural history','museum','learning','related','A way to understand the habitats surrounding your home.','Check hours and special programs.'],
 ['Learn karate','hakone','fitness','intuition','A structured martial-art discipline to compare with movement arts.','Hakone lists Seido Karate for all levels; confirm the current instructor, schedule and suitability.'],
 ['Experience a tea ceremony / tea class','hakone','learning','intuition','A quieter sensory and cultural experiment.','Check the event calendar and reservation requirements.'],
 ['Try a meditation group','hakone','learning','intuition','A quiet, structured practice to contrast with high-skill physical outings.','Hakone lists Zazen meditation; confirm the session and registration. Not a claim of health treatment.'],
 ['Join intertidal citizen science','museum','nature','related','Observe and record biodiversity, rather than merely visiting it.','Program hub only: confirm public eligibility, training and field meeting point. Related to tide pools #5.'],
 ['Help restore estuary habitat','elkhorn','nature','intuition','A hands-on way to support the ecosystems you value.','Volunteer registration and actual work site required; pin is reserve visitor reference.'],
 ['Record underwater sound','pending','creative','intuition','A strong speculative fit: ocean immersion plus filmmaking and sound.','No vetted local guided provider; equipment, permits and safe deployment need planning.'],
 ['Volunteer with animals','spca','nature','intuition','A different practical connection to living things.','Application, training and role availability apply; not a drop-in wildlife handling activity.'],
 ['Learn beekeeping','pending','nature','intuition','A possible food/ecosystem skill beyond gardening.','No suitable current local beginner course verified; not a permission to handle wild hives.'],
 ['Study coastal geology','bridges','nature','intuition','Rock forms, erosion and coastlines add another layer to landscape appreciation.','Observation only; do not collect or damage protected material. Overlap with nature outings, not a second ranked hike.'],
 ['Explore a talus cave','pinnacles','nature','intuition','A distinct landscape experience from an ordinary woodland hike.','Approach requires walking; closures and bats restrict access. Check NPS cave status; overlaps with #19/#20.'],
 ['Ride a heritage steam train','roaring','learning','related','A scenic rail experience as an activity—not an alternative commute or bus suggestion.','Book the intended redwood excursion and check operations.'],
 ['Take an introductory flight','flight','learning','intuition','A different view of the coast and a new technical skill.','Book with an instructor; weather and eligibility apply.'],
 ['Train for kelp-forest monitoring','pending','nature','related','A strong fit for your diving, filming and biodiversity interests.','Reef Check requires diving experience/training; course locations vary. https://www.reefcheck.org/kelp-forest-program/training-course-details/'],
];
Object.assign(venue,{
 gizdich:['Gizdich Ranch · reference entrance',36.9468,-121.7258,'https://www.gizdich-ranch.com/u-pick'],
 garden:['Monterey Community Garden · 293 Van Buren',36.602,-121.8978,'https://sustainablemontereycounty.org/topics/community-gardens/'],
 market:['Old Monterey Farmers Market · Alvarado Street',36.5985,-121.8944,'https://www.oldmonterey.org/oldmonterey/farmers-market-old-monterey-marketplace'],
 rowing:['Los Gatos Rowing Club · Lexington Reservoir',37.2067,-121.9858,'https://lgrc.clubexpress.com/content.aspx?club_id=590251&module_id=720028&page_id=22'],
 shoreline:['Shoreline Lake · Mountain View',37.4327,-122.0872,'https://www.shorelinelake.com/index.html'],
 capoeira:['Raízes do Brasil · 207 McPherson Street, Santa Cruz',36.9598,-122.045,'https://capoeiramonterey.com/'],
 parkour:['Santa Cruz Parkour · 168 Frederick Street',36.9702,-122.0053,'https://www.scparkour.com/'],
 castle:['Castle Rock State Park · entrance reference',37.2317,-122.0957,'https://www.parks.ca.gov/?page_id=29739'],
 ice:['Sharks Ice · San Jose',37.3194,-121.8678,'https://www.sharksiceatsanjose.com/home'],
 trail:['Monterey Coastal Recreation Trail · access reference',36.6088,-121.8945,'https://www.pacificgrove.org/things-to-do/'],
 chess:['Carmel Valley Chess Club · 9 Del Fino Place',36.4794,-121.7322,'https://cvchess.com/'],
 tech:['The Tech Interactive · San Jose',37.3315,-121.8902,'https://www.thetech.org/'],
 cinema:['Lighthouse Cinema · Pacific Grove',36.6209,-121.9187,'https://www.lighthousepgcinema.com/'],
 theatre:['Golden Bough Playhouse · Carmel',36.5517,-121.9246,'https://www.pacrep.org/'],
 sunset:['Sunset Center · Carmel',36.552,-121.9206,'https://www.sunsetcenter.org/'],
 mission:['Carmel Mission',36.5427,-121.9191,'https://carmelmission.org/'],
 planet:['Hartnell Planetarium · campus reference',36.673,-121.6661,'https://www.hartnell.edu/academics-affairs/academics/stem/planetarium/about.html'],
 seymour:['Seymour Marine Discovery Center',36.9496,-122.0653,'https://seymourcenter.ucsc.edu/'],
 elkhorn:['Elkhorn Slough Reserve · visitor entrance',36.8185,-121.7544,'https://www.elkhornslough.org/'],
 spca:['SPCA Monterey County · campus reference',36.5707,-121.7561,'https://www.spcamc.org/'],
 bridges:['Natural Bridges State Beach',36.9514,-122.0577,'https://www.parks.ca.gov/?page_id=541'],
 pinnacles:['Pinnacles west · Balconies approach reference',36.4921,-121.2099,'https://www.nps.gov/pinn/planyourvisit/cavestatus.htm'],
 roaring:['Roaring Camp Railroads · Felton',37.0409,-122.0624,'https://roaringcamp.com/'],
 flight:['Watsonville Airport · United Flight Services',36.9345,-121.7895,'https://united-flight.com/'],
});
const icons='🤿 🌲 🫧 🫁 🐚 🏄 🏃 🛹 🚲 🏄‍♂️ 🐠 📷 🐋 ⛵ 🎣 🏹 📸 🦋 🧗 🌳 ⛺ 🪂 🔭 🚵 🪨 🛶 🐎 ♨️ 🌺 🧹 🔱 🐟 🦀 🌿 🍄 🍓 🥕 🍳 🫙 🧺 🚣 🌬️ 🏊 🥽 🥁 🥷 🎪 🤸 🏋️ 🧘 🌀 🎾 🏓 🏐 🏸 🪶 ⚽ 🌊 🏔️ ⛸️ 🛼 💪 ♟️ 🎲 📚 🗣️ 💻 ⚙️ 🏺 🎨 ✏️ 🔮 💍 🖨️ 🧵 🪵 🖋️ 🎹 🎭 💃 🎬 🎟️ 🎻 🏛️ 🪐 🔬 🦴 🌱 🍵 🕯️ 📋 🪴 🎙️ 🐕 🐝 🪷 🦇 🚂 🛩️ 🪸'.split(' ');
if(rows.length!==70||icons.length!==100||new Set(icons).size!==100)throw new Error(`counts ${rows.length} ${icons.length}`);
const stated=new Set([1,3,4,5,6,7,9,12,14,15,17,20,24,25,26,29]);
data.activities=data.activities.slice(0,30).map(a=>({...a,interestBasis:stated.has(a.id)?'mentioned':'related',kind:a.kind||a.name,accessStatus:'Site reference · check current access'}));
rows.forEach(([name,key,category,interestBasis,why,note],i)=>{const [place,lat,lon,source]=venue[key];data.activities.push({id:i+31,name,kind:name,place,lat,lon,category,interestBasis,why,note,source,unlocated:key==='pending',accessStatus:key==='pending'?'Unmapped · verification needed':'Reference point · confirm entrance / schedule',travel:{}})});
data.activities.forEach((a,i)=>{a.icon=icons[i];a.family=a.category;a.pinAccuracy=a.unlocated?'Unlocated':'Approximate site / campus reference, not a surveyed entrance';});
data.activities.find(a=>a.id===88).icon='🥋';
data.candidateMethod='100 review candidates: mentioned interests, related ideas and intuition-led suggestions. Not 100 proven favorites or a best-in-region ranking. Unverified specialist venues are explicitly unmapped. No private conversations are published.';
fs.writeFileSync(new URL('activity-picks.json',root),JSON.stringify(data.activities.map(({travel,...a})=>a),null,2));
fs.writeFileSync(new URL('map-data.json',root),JSON.stringify(data));
console.log(`${data.activities.length} candidates, ${data.activities.filter(a=>!a.unlocated).length} reference pins; ${data.activities.filter(a=>a.unlocated).length} honest venue gaps.`);
